# coding: utf-8

"""
    BRP bewoning

    API voor het raadplegen van de (historische) bewoning van een adres. 

    The version of the OpenAPI document: 2.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from brp_bewoning_client.api.bewoning_api import BewoningApi


class TestBewoningApi(unittest.TestCase):
    """BewoningApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BewoningApi()

    def tearDown(self) -> None:
        pass

    def test_bewoningen(self) -> None:
        """Test case for bewoningen

        Raadplegen van bewoningen
        """
        pass


if __name__ == '__main__':
    unittest.main()
