# coding: utf-8

"""
    BRP bewoning

    API voor het raadplegen van de (historische) bewoning van een adres. 

    The version of the OpenAPI document: 2.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from brp_bewoning_client.models.bewoning_met_peildatum import BewoningMetPeildatum

class TestBewoningMetPeildatum(unittest.TestCase):
    """BewoningMetPeildatum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BewoningMetPeildatum:
        """Test BewoningMetPeildatum
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BewoningMetPeildatum`
        """
        model = BewoningMetPeildatum()
        if include_optional:
            return BewoningMetPeildatum(
                peildatum = 'Thu Sep 24 01:00:00 CET 1964',
                adresseerbaar_object_identificatie = '0226010000038820'
            )
        else:
            return BewoningMetPeildatum(
                peildatum = 'Thu Sep 24 01:00:00 CET 1964',
                adresseerbaar_object_identificatie = '0226010000038820',
        )
        """

    def testBewoningMetPeildatum(self):
        """Test BewoningMetPeildatum"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
