# coding: utf-8

"""
    BRP bewoning

    API voor het raadplegen van de (historische) bewoning van een adres. 

    The version of the OpenAPI document: 2.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from brp_bewoning_client.models.bewoner import Bewoner

class TestBewoner(unittest.TestCase):
    """Bewoner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Bewoner:
        """Test Bewoner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Bewoner`
        """
        model = Bewoner()
        if include_optional:
            return Bewoner(
                burgerservicenummer = '555555021',
                geheimhouding_persoonsgegevens = True,
                in_onderzoek = True,
                naam = brp_bewoning_client.models.naam.Naam(
                    volledige_naam = 'Pieter Jan de Vries', ),
                geboorte = brp_bewoning_client.models.geboorte_basis.GeboorteBasis(
                    datum = {"type":"Datum","datum":"2018-07-01","langFormaat":"1 juli 2018"}, )
            )
        else:
            return Bewoner(
        )
        """

    def testBewoner(self):
        """Test Bewoner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
