# coding: utf-8

"""
    BRP bewoning

    API voor het raadplegen van de (historische) bewoning van een adres. 

    The version of the OpenAPI document: 2.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from brp_bewoning_client.models.invalid_param import InvalidParam

class TestInvalidParam(unittest.TestCase):
    """InvalidParam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InvalidParam:
        """Test InvalidParam
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InvalidParam`
        """
        model = InvalidParam()
        if include_optional:
            return InvalidParam(
                type = 'https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.5.1',
                name = 'huisnummer',
                code = 'integer',
                reason = 'Waarde is geen geldig getal.'
            )
        else:
            return InvalidParam(
        )
        """

    def testInvalidParam(self):
        """Test InvalidParam"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
