# coding: utf-8

"""
    BRP bewoning

    API voor het raadplegen van de (historische) bewoning van een adres. 

    The version of the OpenAPI document: 2.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from brp_bewoning_client.models.foutbericht import Foutbericht

class TestFoutbericht(unittest.TestCase):
    """Foutbericht unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Foutbericht:
        """Test Foutbericht
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Foutbericht`
        """
        model = Foutbericht()
        if include_optional:
            return Foutbericht(
                type = '',
                title = 'żjiÞr÷ÜŮBrAŷŅŊĲĦ71ĒGý',
                status = 100,
                detail = 'Ŵâķ7YİĽyļĞpŹTĒřsńĉųřqĢÔųÝnÑíÒÑńĔÎ63Ŏ7æżÏŎÌÊuçŝğġĽąėĆŻĿĆÛāĪ1āşTđíÇûŎBĻåüĝÑĤQōŇšŲďIĸTŏ1jĽŸŌĄĘUS9ùÙĵŏĥ÷ű',
                instance = '',
                code = 'C'
            )
        else:
            return Foutbericht(
        )
        """

    def testFoutbericht(self):
        """Test Foutbericht"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
