# coding: utf-8

"""
    BRP bewoning

    API voor het raadplegen van de (historische) bewoning van een adres. 

    The version of the OpenAPI document: 2.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from brp_bewoning_client.models.bewoningen_query_response import BewoningenQueryResponse

class TestBewoningenQueryResponse(unittest.TestCase):
    """BewoningenQueryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BewoningenQueryResponse:
        """Test BewoningenQueryResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BewoningenQueryResponse`
        """
        model = BewoningenQueryResponse()
        if include_optional:
            return BewoningenQueryResponse(
                bewoningen = [
                    brp_bewoning_client.models.bewoning.Bewoning(
                        adresseerbaar_object_identificatie = '0226010000038820', 
                        periode = brp_bewoning_client.models.periode.Periode(
                            datum_van = 'Wed Jan 01 01:00:00 CET 2020', 
                            datum_tot = 'Fri Jan 01 01:00:00 CET 2021', ), 
                        bewoners = [
                            brp_bewoning_client.models.bewoner.Bewoner(
                                burgerservicenummer = '555555021', 
                                geheimhouding_persoonsgegevens = True, 
                                in_onderzoek = True, 
                                naam = brp_bewoning_client.models.naam.Naam(
                                    volledige_naam = 'Pieter Jan de Vries', ), 
                                geboorte = brp_bewoning_client.models.geboorte_basis.GeboorteBasis(
                                    datum = {"type":"Datum","datum":"2018-07-01","langFormaat":"1 juli 2018"}, ), )
                            ], 
                        mogelijke_bewoners = [
                            brp_bewoning_client.models.bewoner.Bewoner()
                            ], 
                        indicatie_veel_bewoners = True, )
                    ]
            )
        else:
            return BewoningenQueryResponse(
        )
        """

    def testBewoningenQueryResponse(self):
        """Test BewoningenQueryResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
