# coding: utf-8

# flake8: noqa

"""
    BRP bewoning

    API voor het raadplegen van de (historische) bewoning van een adres. 

    The version of the OpenAPI document: 2.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from brp_bewoning_client.api.bewoning_api import BewoningApi

# import ApiClient
from brp_bewoning_client.api_response import ApiResponse
from brp_bewoning_client.api_client import ApiClient
from brp_bewoning_client.configuration import Configuration
from brp_bewoning_client.exceptions import OpenApiException
from brp_bewoning_client.exceptions import ApiTypeError
from brp_bewoning_client.exceptions import ApiValueError
from brp_bewoning_client.exceptions import ApiKeyError
from brp_bewoning_client.exceptions import ApiAttributeError
from brp_bewoning_client.exceptions import ApiException

# import models into sdk package
from brp_bewoning_client.models.abstract_datum import AbstractDatum
from brp_bewoning_client.models.bad_request_foutbericht import BadRequestFoutbericht
from brp_bewoning_client.models.bewoner import Bewoner
from brp_bewoning_client.models.bewoning import Bewoning
from brp_bewoning_client.models.bewoning_met_peildatum import BewoningMetPeildatum
from brp_bewoning_client.models.bewoning_met_periode import BewoningMetPeriode
from brp_bewoning_client.models.bewoningen_query import BewoningenQuery
from brp_bewoning_client.models.bewoningen_query_response import BewoningenQueryResponse
from brp_bewoning_client.models.datum_onbekend import DatumOnbekend
from brp_bewoning_client.models.foutbericht import Foutbericht
from brp_bewoning_client.models.geboorte_basis import GeboorteBasis
from brp_bewoning_client.models.invalid_param import InvalidParam
from brp_bewoning_client.models.jaar_datum import JaarDatum
from brp_bewoning_client.models.jaar_maand_datum import JaarMaandDatum
from brp_bewoning_client.models.naam import Naam
from brp_bewoning_client.models.periode import Periode
from brp_bewoning_client.models.volledige_datum import VolledigeDatum
